development:
  adapter: postgresql
  encoding: unicode
  database: auth_development
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['AUTH_PASSWORD'] %>
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: auth_test
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['AUTH_PASSWORD'] %>
  port: 5433
