development:
  adapter: postgresql
  encoding: unicode
  database: tasks_development
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['TASKS_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: tasks_test
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['TASKS_PASSWORD'] %>