development:
  adapter: postgresql
  encoding: unicode
  database: accounting_development
  host: localhost
  pool: 5
  port: 5434
  username: postgres
  password: <%= ENV['ACCOUNTING_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: accounting_test
  host: localhost
  pool: 5
  port: 5434
  username: postgres
  password: <%= ENV['ACCOUNTING_PASSWORD'] %>