development:
  adapter: postgresql
  encoding: unicode
  database: analytics_development
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['ANALYTICS_DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: analytics_test
  host: localhost
  pool: 5
  username: postgres
  password: <%= ENV['ANALYTICS_DB_PASSWORD'] %>